name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bookswap
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, dom
        coverage: none
        tools: composer:v2

    - name: Check PHP and Composer versions
      run: |
        php -v
        composer -V

    - name: Change to project directory
      run: |
        pwd
        ls -la
        cd project
        pwd
        ls -la

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./project

    - name: Install Dependencies
      run: composer install -v
      working-directory: ./project

    - name: Generate key
      run: php artisan key:generate
      working-directory: ./project

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./project

    - name: Run Database Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: bookswap
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force
      working-directory: ./project

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: rafliafrz/bookswap:latest
